services:
  - type: web
    name: tacbarber-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_HOST
        value: dpg-d4mokdje5dus738h49m0-a.frankfurt-postgres.render.com
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: tacbarber
      - key: DATABASE_USER
        value: tacbarber
      - key: DATABASE_PASSWORD
        value: kx9aB6bkJEUUIzBYq1NIDQtdhgKeG71e
      - key: QUARKUS_PROFILE
        value: prod
